name: Blog

on:
  schedule:
  - cron: '0 8 * * *'

jobs:
  blog:
    name: Blog
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@main
        with:
          feed-url: 'https://youngchief.tk/blog.rss'
          readme-section: blog
          empty-commits: false